name: "Labeler"
on:
- pull_request

jobs:
  label:
    runs-on: self-hosted
    steps:
    - uses: actions/labeler@v2
      if: github.base_ref == null
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
